# Generated by Django 4.2.8 on 2024-04-22 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.IntegerField()),
                ('subgroup_code', models.IntegerField()),
                ('group_name', models.TextField()),
                ('subgroup_name', models.TextField()),
                ('food_code', models.IntegerField()),
                ('food_name', models.TextField()),
                ('water', models.SmallIntegerField()),
                ('protein', models.SmallIntegerField()),
                ('carbohydrates', models.SmallIntegerField()),
                ('fats', models.SmallIntegerField()),
                ('sugars', models.SmallIntegerField()),
                ('glucose', models.SmallIntegerField()),
                ('lactose', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField(max_length=50)),
                ('insertion_date', models.DateField()),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.user')),
                ('weight', models.FloatField()),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('objective', models.IntegerField(choices=[(1, 'Maintenance'), (2, 'Muscle gain'), (3, 'Fat loss')])),
                ('allergies', models.IntegerField(choices=[(1, 'Celiac disease'), (2, 'Lactose intolerant'), (3, 'None')])),
            ],
            bases=('backend.user',),
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client')),
            ],
        ),
        migrations.CreateModel(
            name='FoodIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('meal', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Meal', 'Meal'), ('Snack', 'Snack'), ('Dinner', 'Dinner')], max_length=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.food')),
                ('weeklyMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.weeklymenu')),
            ],
            options={
                'unique_together': {('weeklyMenu', 'food')},
            },
        ),
    ]
