# Generated by Django 4.2.8 on 2024-06-05 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.IntegerField(null=True)),
                ('subgroup_code', models.IntegerField(null=True)),
                ('group_name', models.TextField(null=True)),
                ('subgroup_name', models.TextField(null=True)),
                ('food_code', models.IntegerField(null=True)),
                ('food_name', models.TextField(null=True)),
                ('water', models.SmallIntegerField(null=True)),
                ('protein', models.SmallIntegerField(null=True)),
                ('carbohydrates', models.SmallIntegerField(null=True)),
                ('fats', models.SmallIntegerField(null=True)),
                ('sugars', models.SmallIntegerField(null=True)),
                ('glucose', models.SmallIntegerField(null=True)),
                ('lactose', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_code_one', models.IntegerField()),
                ('food_code_two', models.IntegerField()),
                ('group_code_one', models.IntegerField()),
                ('group_code_two', models.IntegerField()),
                ('calories', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=10)),
                ('insertion_date', models.DateField(default=django.utils.timezone.now)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.user')),
                ('number_meals', models.TextField()),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=20)),
                ('activity', models.CharField(choices=[('Sedentary', 'Sedentary'), ('Light activity', 'Light activity'), ('Moderate activity', 'Moderate activity'), ('Daily exercise', 'Daily exercise'), ('Intense exercise', 'Intense exercise')], default='Sedentary', max_length=20)),
                ('goal', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Muscle gain', 'Muscle gain'), ('Fat loss', 'Fat loss')], default='Maintenance', max_length=20)),
                ('allergies', models.CharField(choices=[('None', 'None'), ('Celiac disease', 'Celiac disease'), ('Lactose intolerant', 'Lactose intolerant'), ('Seafood', 'Seafood'), ('Egg allergy', 'Egg allergy')], default='None', max_length=20)),
            ],
            bases=('backend.user',),
        ),
        migrations.CreateModel(
            name='FoodIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('meal', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Meal', 'Meal'), ('Snack', 'Snack'), ('Dinner', 'Dinner')], max_length=10)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.food')),
                ('weeklyMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.weeklymenu')),
            ],
        ),
        migrations.AddField(
            model_name='weeklymenu',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client'),
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client')),
            ],
        ),
    ]
