from .allergies import Allergies
from .user import User
from .client import Client
from .dayOfWeek import DayOfWeek
from .food import Food
from .foodIntake import FoodIntake
from .meal import Meal
from .goal import Goal
from .requests import Requests
from .weeklyMenu import WeeklyMenu
from .gender import Gender